[build]
  command = "yarn build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"
  NODE_OPTIONS = "--no-experimental-fetch"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 